analyseur:
		javac -sourcepath ./src -d bin ./src/Main/*.java ./src/Protocole/*.java ./src/TraitementFichier/*.java ./src/Main/*.java ./src/InterfaceGraphique/*.java
		java -cp bin src/Main/Main.java
